version: "3.3"
services:
  nodered:
    image: "nodered/node-red"
    ports:
      - "1880:1880"
      - "2000:2000"
      - "1999:1999"
      - "1998:1998"
    volumes:
      - node-red_data:/data
    restart: always
  minio:
    image: "pixelchrome/minio-arm"
    command: server --console-address ":9001" http:///minio_data
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    restart: always
volumes:
  node-red_data:
        external: true
  minio_data:
        external: true
networks:
    default:
        external:
            name: mynet
